In [88]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as ply
from scipy.stats  import ttest_rel, ttest_ind
import itertools as it
%matplotlib inline

In [4]:
df = pd.read_excel(r'D:\Yuri\Projects\DSS_169_increased_marketplaces_discount\leads_qty_and_avg_check_AUG.xlsx')

In [5]:
df

,country,product,lead_qty,check_usd,discount_lead_qty,discount_check_usd
0,Chile,Black Latte Drink Mix,15,54.236286,11,58.731257
1,Chile,Duston Gel,27,39.332467,44,35.135449
2,Chile,Gyronix,2,41.963705,3,58.179866
3,Chile,Incasol,186,42.702902,31,41.912488
4,Chile,Inno Gialuron,64,43.619800,52,31.007385
5,Chile,Money Amulet,2,34.221738,3,37.076875
6,Chile,Motion Free,48,37.306803,49,33.574522
7,Chile,Rechiol,6,35.632166,6,35.628652
8,Chile,Varikosette,25,34.645448,27,30.863321
9,Chile,Yaconia,30,45.746632,31,41.212445
10,Colombia,Duston Gel,5,32.953676,6,36.484588
11,Colombia,Flexiton,1,30.659790,8,33.786598
12,Colombia,Inno Gialuron,4,33.889389,3,26.410346
13,Colombia,Motion Free,11,35.590511,3,31.038753
14,Colombia,Rechiol,27,28.473793,19,27.225823
15,Colombia,Sorax,5,33.120567,6,31.848341
16,Mexico,Biadit,150,44.283694,159,46.690086
17,Mexico,Caro Crystall,73,44.973984,82,42.224030
18,Mexico,Leveren,143,46.547832,58,46.173382
19,Mexico,Poweronix,3,64.261088,3,76.665466
20,Mexico,Zipka,1,47.366893,1,39.125978
21,Peru,Black Latte Drink Mix,1,64.873950,1,28.617798
22,Peru,Flekosteel,9,41.869022,12,56.685781
23,Peru,Incas Protect,2,60.980106,1,33.992641
24,Peru,Inno Gialuron expert,7,26.936425,12,34.088913
25,Peru,Ketoxide,2,32.056524,3,27.102842
26,Peru,Leveren,2,37.611793,3,31.467978
27,Peru,Motion Free,4,32.508465,8,28.449066
28,Peru,Ocellus,3,35.334546,3,39.797835
29,Peru,Rechiol,2,34.268535,2,28.990372
30,Peru,Varikosette,8,35.688347,6,31.756983
31,Peru,Yaconia,1,113.147051,3,41.972480

In [10]:
std_df = pd.read_excel(r'D:\Yuri\Projects\DSS_169_increased_marketplaces_discount\DSS_169_increased_marketplaces_discount_with_STD.xlsx')

In [26]:
std_df = std_df.drop_duplicates()

In [28]:
std_df.reset_index(inplace=True)
std_df

,level_0,index,country,product,lead_qty,check_usd,std,discount_lead_qty,discount_check_usd,std_discount
0,0,0,Chile,Black Latte Drink Mix,15,54.236286,0.500000,11,58.731257,0.517549
1,1,72,Chile,Duston Gel,27,39.332467,1.293340,44,35.135449,1.869556
2,2,237,Chile,Gyronix,2,41.963705,0.000000,3,58.179866,0.707107
3,3,241,Chile,Incasol,186,42.702902,57.504348,31,41.912488,1.164500
4,4,349,Chile,Inno Gialuron,64,43.619800,2.313521,52,31.007385,1.995232
5,5,574,Chile,Money Amulet,2,34.221738,0.000000,3,37.076875,0.000000
6,6,580,Chile,Motion Free,48,37.306803,2.144761,49,33.574522,1.387015
7,7,805,Chile,Rechiol,6,35.632166,0.000000,6,35.628652,0.000000
8,8,841,Chile,Varikosette,25,34.645448,1.489356,27,30.863321,0.828742
9,9,995,Chile,Yaconia,30,45.746632,1.566699,31,41.212445,1.556624
10,10,1151,Colombia,Duston Gel,5,32.953676,0.500000,6,36.484588,0.000000
11,11,1175,Colombia,Flexiton,1,30.659790,NaN,8,33.786598,0.894427
12,12,1180,Colombia,Inno Gialuron,4,33.889389,0.577350,3,26.410346,0.000000
13,13,1189,Colombia,Motion Free,11,35.590511,0.517549,3,31.038753,0.000000
14,14,1213,Colombia,Rechiol,27,28.473793,1.356801,19,27.225823,0.567646
15,15,1333,Colombia,Sorax,5,33.120567,0.577350,6,31.848341,0.447214
16,16,1348,Mexico,Biadit,150,44.283694,4.259443,159,46.690086,4.482567
17,17,1558,Mexico,Caro Crystall,73,44.973984,8.659223,82,42.224030,3.278300
18,18,1670,Mexico,Leveren,143,46.547832,4.673125,58,46.173382,1.703261
19,19,1880,Mexico,Poweronix,3,64.261088,0.707107,3,76.665466,0.000000
20,20,1886,Mexico,Zipka,1,47.366893,NaN,1,39.125978,NaN
21,21,1887,Peru,Black Latte Drink Mix,1,64.873950,NaN,1,28.617798,NaN
22,22,1888,Peru,Flekosteel,9,41.869022,1.303840,12,56.685781,0.500000
23,23,1933,Peru,Incas Protect,2,60.980106,0.000000,1,33.992641,NaN
24,24,1935,Peru,Inno Gialuron expert,7,26.936425,0.408248,12,34.088913,0.534522
25,25,1983,Peru,Ketoxide,2,32.056524,NaN,3,27.102842,0.000000
26,26,1986,Peru,Leveren,2,37.611793,0.000000,3,31.467978,0.000000
27,27,1992,Peru,Motion Free,4,32.508465,0.000000,8,28.449066,0.377964
28,28,2020,Peru,Ocellus,3,35.334546,0.000000,3,39.797835,0.000000
29,29,2029,Peru,Rechiol,2,34.268535,0.000000,2,28.990372,NaN
30,30,2031,Peru,Varikosette,8,35.688347,0.516398,6,31.756983,0.577350
31,31,2055,Peru,Yaconia,1,113.147051,NaN,3,41.972480,0.707107

In [30]:
std_df = std_df.drop(['level_0', 'index'], axis=1)

In [36]:
std_df = std_df.dropna()
std_df

,country,product,lead_qty,check_usd,std,discount_lead_qty,discount_check_usd,std_discount
0,Chile,Black Latte Drink Mix,15,54.236286,0.500000,11,58.731257,0.517549
1,Chile,Duston Gel,27,39.332467,1.293340,44,35.135449,1.869556
2,Chile,Gyronix,2,41.963705,0.000000,3,58.179866,0.707107
3,Chile,Incasol,186,42.702902,57.504348,31,41.912488,1.164500
4,Chile,Inno Gialuron,64,43.619800,2.313521,52,31.007385,1.995232
5,Chile,Money Amulet,2,34.221738,0.000000,3,37.076875,0.000000
6,Chile,Motion Free,48,37.306803,2.144761,49,33.574522,1.387015
7,Chile,Rechiol,6,35.632166,0.000000,6,35.628652,0.000000
8,Chile,Varikosette,25,34.645448,1.489356,27,30.863321,0.828742
9,Chile,Yaconia,30,45.746632,1.566699,31,41.212445,1.556624
10,Colombia,Duston Gel,5,32.953676,0.500000,6,36.484588,0.000000
12,Colombia,Inno Gialuron,4,33.889389,0.577350,3,26.410346,0.000000
13,Colombia,Motion Free,11,35.590511,0.517549,3,31.038753,0.000000
14,Colombia,Rechiol,27,28.473793,1.356801,19,27.225823,0.567646
15,Colombia,Sorax,5,33.120567,0.577350,6,31.848341,0.447214
16,Mexico,Biadit,150,44.283694,4.259443,159,46.690086,4.482567
17,Mexico,Caro Crystall,73,44.973984,8.659223,82,42.224030,3.278300
18,Mexico,Leveren,143,46.547832,4.673125,58,46.173382,1.703261
19,Mexico,Poweronix,3,64.261088,0.707107,3,76.665466,0.000000
22,Peru,Flekosteel,9,41.869022,1.303840,12,56.685781,0.500000
24,Peru,Inno Gialuron expert,7,26.936425,0.408248,12,34.088913,0.534522
26,Peru,Leveren,2,37.611793,0.000000,3,31.467978,0.000000
27,Peru,Motion Free,4,32.508465,0.000000,8,28.449066,0.377964
28,Peru,Ocellus,3,35.334546,0.000000,3,39.797835,0.000000
30,Peru,Varikosette,8,35.688347,0.516398,6,31.756983,0.577350

In [44]:
describe_df = pd.DataFrame()
list_of_t = []
for i in std_df['country'].unique():
    for j in std_df[std_df['country'] == i]['product'].unique():
        test = std_df[(std_df['country'] == i) & (std_df['product'] == j)]
        x1 = test['lead_qty']
        x2 = test['discount_lead_qty']
        sd1 = test['std']
        sd2 = test['std_discount']
        n1 = 15
        n2 = 15
        se = np.sqrt((sd1**2 / n1) + (sd2**2 / n2))
        t_value = np.abs((x1 - x2)/se)
        list_of_t.append(t_value)

In [99]:
list_of_t

[0    21.527849
 dtype: float64,
 1    28.962414
 dtype: float64,
 2    5.477226
 dtype: float64,
 3    10.437287
 dtype: float64,
 4    15.212777
 dtype: float64,
 5    inf
 dtype: float64,
 6    1.516334
 dtype: float64,
 7   NaN
 dtype: float64,
 8    4.544676
 dtype: float64,
 9    1.753644
 dtype: float64,
 10    7.745967
 dtype: float64,
 12    6.708204
 dtype: float64,
 13    59.866518
 dtype: float64,
 14    21.066587
 dtype: float64,
 15    5.303301
 dtype: float64,
 16    5.637031
 dtype: float64,
 17    3.764638
 dtype: float64,
 18    66.18686
 dtype: float64,
 19    0.0
 dtype: float64,
 22    8.320503
 dtype: float64,
 24    28.791446
 dtype: float64,
 26    inf
 dtype: float64,
 27    40.987803
 dtype: float64,
 28   NaN
 dtype: float64,
 30    10.0
 dtype: float64]

In [47]:
gr1 = std_df[['country', 'product', 'lead_qty']]
gr2 = std_df[['country', 'product', 'discount_lead_qty']]

## По странам

In [128]:
discounts = pd.read_excel(r'D:\Yuri\Projects\DSS_169_increased_marketplaces_discount\final_discounts.xlsx')
discounts

    ts_spawn_date country                product  lead_qty
0      2022-08-01   Chile  Black Latte Drink Mix         2
1      2022-08-03   Chile  Black Latte Drink Mix         2
2      2022-08-06   Chile  Black Latte Drink Mix         2
3      2022-08-07   Chile  Black Latte Drink Mix         1
4      2022-08-08   Chile  Black Latte Drink Mix         2
..            ...     ...                    ...       ...
427    2022-08-22    Peru            Varikosette         1
428    2022-08-25    Peru            Varikosette         1
429    2022-08-15    Peru                Yaconia         1
430    2022-08-17    Peru                Yaconia         2
431    2022-08-23    Peru                Yaconia         1

[432 rows x 4 columns]

In [135]:
countries_df = discounts.groupby(['ts_spawn_date', 'country'], as_index=False).agg({'lead_qty': sum})
countries_df = countries_df.query('country == ["Chile", "Mexico", "Peru"]')
countries_df = countries_df.head(84)
countries_df = countries_df.query('ts_spawn_date != ["2022-08-02", "2022-08-08", "2022-08-09", "2022-08-10", "2022-08-18", "2022-08-21", "2022-08-23"]')

In [136]:
result_list = []
for i in countries_df['country'].unique():
    test = countries_df[(countries_df['country'] == i)]
    group1 = test[['ts_spawn_date', 'country', 'lead_qty']]
    group1 = group1.query('ts_spawn_date < "2022-08-16"')
    group2 = test[['ts_spawn_date', 'country', 'lead_qty']]
    group2 = group2.query('ts_spawn_date > "2022-08-15"')
    result_list.append(ttest_rel(group1['lead_qty'], group2['lead_qty']))

In [137]:
result_list

[Ttest_relResult(statistic=-0.9187930694345933, pvalue=0.3798320632878954),
 Ttest_relResult(statistic=-0.5170542049716025, pvalue=0.6163605661674557),
 Ttest_relResult(statistic=-1.3921151159742613, pvalue=0.19406985968944931)]